default: heartbeat.pdf

heartbeat.pdf: heartbeat.tex
	pdflatex heartbeat.tex
	pdflatex heartbeat.tex

clean:
	rm -f heartbeat.log heartbeat.out heartbeat.toc heartbeat.aux heartbeat.nav heartbeat.snm heartbeat.vrb heartbeat.pdf

