default: wireshark.pdf

wireshark.pdf: wireshark.tex
	pdflatex wireshark.tex
	pdflatex wireshark.tex

clean:
	rm -f wireshark.log wireshark.out wireshark.toc wireshark.aux wireshark.nav wireshark.snm wireshark.vrb wireshark.pdf

